### ISSUE TITLE
DIAGRAMA DE CLASES SMART CONTRACT

### ISSUE THREAD

**Issue by ToniDepp** [SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-nuggets-de-pollo#1]
[DC-EQUIPO2-IS-6US.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diagrama-de-clases-nuggets-de-pollo/files/14672917/DC-EQUIPO2-IS-6US.pdf)

**Comment by saul19bautista** [comment]
portada : 25
procedimiento 👍 25
figuras 👍 25
resultado  y conclusiones 👍 25
 calificacion 👍 20/20

**Comment by josealfredo79** [comment]
bien hecho y revisado..solo que se necesita la codificación de atributos y métodos...
